### ISSUE TITLE
Fix error treatment calling todo!() and crashing in non-exhaustive match.

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#29]

**Comment by GabrielSimonetto** [comment]
This issue is regarding the impl fmt::Display for Error on error.rs

```
            Error::OofError(err) => FinalError::with_title(err),
            Error::IoError { reason } => FinalError::with_title(reason),
           ...
            _err => {
                todo!();
            }
```

Missing display messages:

- [ ] - UnknownExtensionError(String)
- [x] - MissingExtensionError(PathBuf)
- [x] - IoError { reason: String }
- [x] - FileNotFound(PathBuf)
- [ ] - AlreadyExists
- [ ] - InvalidZipArchive(&'static str)
- [ ] - PermissionDenied
- [ ] - UnsupportedZipArchive(&'static str)
- [x] - InternalError
- [x] - OofError(oof::OofError)
- [x] - CompressingRootFolder
- [x] - MissingArgumentsForCompression
- [x] - CompressionTypo
- [x] - WalkdirError { reason: String }

It would be neat to tackle this as soon as possible because dropping the wildcard match forces us to add the error messages as soon as a new error enum is created, and as is, the pile could just grow forever unattended :pineapple:

**Comment by marcospb19** [comment]
Wow, nice checklist.

This is a priority, however, this issue is blocked by #56, that one needs to be resolved first.

That's because a lot of the work necessary to solve this issue would have to be discarded and remade after #56, because `fs-err` will change our error messages.

**Comment by GabrielSimonetto** [comment]
#56 is solved so this is not blocked anymore d:

**Comment by GabrielSimonetto** [comment]
I will paste here a way to trigger one of the untreated errors, since it might be useful to someone, the error in particular is the `NotFound`

```
impl From<std::io::Error> for Error {
    fn from(err: std::io::Error) -> Self {
        match err.kind() {
            std::io::ErrorKind::NotFound => todo!(),
```

Currently this error just panics:

```
thread 'main' panicked at 'not yet implemented', src/error.rs:161:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The way to trigger it is to delete the file you are trying to decompress after the program has checked that it exists, you can do that inserting a sleep [after the command check](https://github.com/ouch-org/ouch/blob/master/src/commands.rs#L148):

```
        Subcommand::Decompress { files, output: output_folder } => {
            std::thread::sleep(std::time::Duration::from_secs(10));
```

Then, while it sleeps you remove the zip that you are working with
